[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 100 

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
